### ISSUE TITLE
App container cant be build

### ISSUE THREAD

**Issue by K2ouMais** [WendellAdriel/laravel-exa#6] opened 2023-05-10 20:51 UTC
When using the command ```make configure``` to start the application and while the images are beeing build, seems that the following command isnt working:

```
RUN composer install --prefer-dist && rm -rf /root/.composer
```

After a while (>300s) it will fail.

Try to delete the built images on your system and run ```make configure```.

Thanks

**Comment by WendellAdriel** [comment] 2023-05-11 13:07
I was able to identify some issues in the initial configuration and released a new version v1.4.0.
Can you check the README that has now been updated on how to configure the app and try again to see if it's working, please @K2ouMais?

I tried here in my machine and it's working without issues, but I prefer that you check on your side before closing this.

**Comment by K2ouMais** [comment] 2023-05-11 15:20
Ok, this is what I tried:
- Installed your package
- Build the images with "make build"
- Tried to configure the package with "make configure" and get an error...

![Screenshot 2023-05-11 170249](https://github.com/WendellAdriel/laravel-exa/assets/52510455/e8ad3646-868a-4555-a437-a41a5cb86e1b)

One other thing is, that you are using make commands in the makefile, which is ok fine, but this generates this output between the make commands:
![Makefile](https://github.com/WendellAdriel/laravel-exa/assets/52510455/0f8b5cb8-e88b-4e04-8426-c617a9958c42)
These arent errors, but you can get rid of it using the following argument:
make ```--no-print-directory``` command

Other than that, everything seems to work well:
![image](https://github.com/WendellAdriel/laravel-exa/assets/52510455/8a0db196-c8a4-491d-ab50-f014b834a3d4)
The only thing is, that for some reason the main image is 1.2GB, which is a lot of used space and could be reduced using alpine images, but it could be because you have everything in one container.

**Comment by WendellAdriel** [comment] 2023-05-12 10:41
This error is really weird because I could not reproduce this here.
That's true, the alpine images can make it smaller, but I didn't have time to test yet.
If you have some time to test out and help a PR would be great! 😉

**Comment by WendellAdriel** [comment] 2023-05-19 10:04
@K2ouMais I just released a new version switching the images used by the API and Redis to use their Alpine versions. Can you check if you're still facing issues with this new release?

**Comment by WendellAdriel** [comment] 2024-03-28 16:40
Closing due to inactivity

**Closed as completed by WendellAdriel** 2024-03-28 16:40 UTC
Labels: bug
